# Generated by Django 3.2.7 on 2021-09-25 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HTSW', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routes',
            old_name='r_filename',
            new_name='r_stops',
        ),
    ]
