# Generated by Django 3.2.7 on 2021-09-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HTSW', '0002_rename_r_filename_routes_r_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='r_count_stowaways',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
